import {  Forum } from "next/font/google";
import "./globals.css";


const forum = Forum({ subsets: ["latin"] });

export const metadata = {
  title: "Luxury Trips",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={forum.className}>
        
        {children}
        
        </body>
    </html>
  );
}
